### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by cori** [dive2Pro/roam-tabs#1]
Couldn't leave an issue on the Roam repo PR, and maybe this is intentional, but https://github.com/Roam-Research/roam-depot/pull/705 is missing extension name and author, so it shows up in Roam like this

<img width="774" alt="image" src="https://github.com/dive2Pro/roam-tabs/assets/46317/e56b918c-e6e4-4675-973b-08afa024099c">

**Comment by dive2Pro** [comment]
thank you for reporting this. It should be fixed now.

**Comment by cori** [comment]
LGTM, thanks!
