### ISSUE TITLE
Top-Right Roam menu icon can not select when enable roam-tabs

### ISSUE THREAD

**Issue by xiaofeng1986** [dive2Pro/roam-tabs#4]
![image](https://github.com/dive2Pro/roam-tabs/assets/6204598/71fb142b-66d7-4648-b27e-446c28a355f8)

Your roam plugin is very awesome and just solve my problem by quickly switching recent pages. But there is a little issue please help to check. 

The top-right menu like search , calendar, adjust width or settings can not selected by pointer when enable roam-tabs , it could work when disabled. 

Noticed the tab line are below the menu bar during the readme , but my menu bar is in the same line . Not sure this is my personal issue or normal issue . Switch another browser like safari is the same.

OS: Macos 14.0 
Browser: Arc Version 1.11.0 (42160), Chromium Engine Version 117.0.5938.149

**Comment by dive2Pro** [comment]
which theme do you use?

**Comment by xiaofeng1986** [comment]
I use the below theme by roam team favorite  in the Help Graph. It is OK now when disable the below theme.
It conflict the plugin when enable the first material-palenight-roam.css. 
Do you have any idea about it?

`roam/css 

@import url('https://abhayprasanna.github.io/material-palenight-roam.css');
@import url('https://abhayprasanna.github.io/rainbow-indent.css');
@import url('https://abhayprasanna.github.io/dark-masonry.css') (min-width:700px);
`

![image](https://github.com/dive2Pro/roam-tabs/assets/6204598/0f34706d-bee2-48ac-8c8b-a2c85cae2dbe)

**Comment by dive2Pro** [comment]
hey, i think is   
`@import url('https://abhayprasanna.github.io/material-palenight-roam.css');`, 

you can add this line of code in your graph to solve this  
.rm-files-dropzone {  
 display: contents;  
}
